In [1]:
import random
import time
import numpy as np


In [4]:
a=[]
for i in range (100000000):
    a.append(random.random())
t1=time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t3=time.time()
sum2=np.sum(b)
t4=time.time()
print(t2-t1,t4-t3)

0.3125894069671631 0.06301116943359375


In [5]:
list1=[1,2,3,4]
oneArray=np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
t2=np.array(range(10))
print(t2)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
t3=np.arange(0,10,2)
print(t3)

[0 2 4 6 8]


In [10]:
list2 = [[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
print(twoArray)
print(twoArray.ndim)
print(twoArray.shape)
print(twoArray.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [13]:
four=np.array([[1,2,3],[4,5,6]])
print(four)
four.shape=(3,2)
print(four)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
four=four.reshape(3,2)
print(four)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
five=four.reshape((6,),order='F')
six=four.flatten(order='F')
print(five)
print(six)

[1 3 5 2 4 6]
[1 3 5 2 4 6]


In [17]:
t=np.arange(24)
print(t)
print(t.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [28]:
t1=t.reshape((4,6))
t2=t.reshape((2,3,4))
print(t1)
print(t1.shape)
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
a=np.array([9,12,88,14,25])
list_a=a.tolist()
print(list_a)

[9, 12, 88, 14, 25]


In [23]:
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)
print(f.dtype)


2
int16


In [24]:
f1=f.astype(np.int64)
print(f1.dtype)

int64


In [26]:
print(round(random.random(),2))
arr=np.array([random.random() for i in range(10)])
print(np.round(arr,2))

0.18
[0.09 0.54 0.55 0.27 0.05 0.78 0.7  0.95 0.06 0.82]


In [32]:
t1=np.arange(24).reshape((6,4))
print(t1)
print(t1+2)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [33]:
t1=np.arange(24).reshape((6,4))
t2=np.arange(100,124).reshape((6,4))
print(t1+t2)
print(t1*t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [35]:
t1 =np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1-t2)

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [36]:
t1 =np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [37]:
a=np.array([[1,2,4],[4,5,6]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.sum(a))

[ 5  7 10]
[ 7 15]
22


In [38]:
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的)print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


In [45]:
t = np.arange( 24 ).reshape( 4, 6 )

t[1, :] = 0
print(t)

t[:, 1] = 0
print(t)

t[1:3]=0
print(t)

t[:,1:4]=1
print(t)

t[t<10]=2
print(t)

[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0 20 21 22 23]]
[[ 0  1  1  1  4  5]
 [ 0  1  1  1  0  0]
 [ 0  1  1  1  0  0]
 [18  1  1  1 22 23]]
[[ 2  2  2  2  2  2]
 [ 2  2  2  2  2  2]
 [ 2  2  2  2  2  2]
 [18  2  2  2 22 23]]


In [51]:
score = np.array( [[80, 88],[82, 81], [75, 81]] )
result = np.where( score > 80,True,False)
print(result)

[[False  True]
 [ True  True]
 [False  True]]


In [53]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [54]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [55]:
a=np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [65]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u1,indices = np.unique(a,return_inverse = True)
print (u1)
print (indices)
print ('\n')
print ('返回去重元素的出现次数：')
u2,indices = np.unique(a,return_counts = True)
print (u2)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的出现次数：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [59]:
score =np.array([[80,88],[82,81],[75,81]])
res=np.max(score)
print(res)
res=np.max(score,axis=0)
print(res)
res = np.min(score)
print(res)
res = np.min(score,axis=0)
print(res)

88
[82 88]
75
[75 81]


In [60]:
result = np.maximum( [-2,-1, 0, 1, 2], 0 ) 
print(result)
result = np.minimum( [-2,-1, 0, 1, 2], 0 ) 
print(result)
result = np.maximum( [-2,-1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)

[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]


In [69]:
res=np.mean(score)
print(res)
res1=np.mean(score,axis=0)
print(res1)
arr= np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
print(arr.cumsum(1))

81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [70]:
result = np.argmin(score,axis=0)
res=np.min(score,axis=0)
print(result,res)

[2 1] [75 81]


In [71]:
result = np.std(score,axis=0)
print(result)

[2.94392029 3.29983165]


In [73]:
result = np.ptp(score,axis=0)#就是最大值和最小值的差
print(result)

[7 7]
