In [1]:
import random
import time
import numpy as np


In [4]:
a=[]
for i in range (100000000):
    a.append(random.random())
t1=time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t3=time.time()
sum2=np.sum(b)
t4=time.time()
print(t2-t1,t4-t3)

0.3125894069671631 0.06301116943359375


In [5]:
list1=[1,2,3,4]
oneArray=np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
t2=np.array(range(10))
print(t2)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
t3=np.arange(0,10,2)
print(t3)

[0 2 4 6 8]


In [10]:
list2 = [[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
print(twoArray)
print(twoArray.ndim)
print(twoArray.shape)
print(twoArray.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [13]:
four=np.array([[1,2,3],[4,5,6]])
print(four)
four.shape=(3,2)
print(four)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
four=four.reshape(3,2)
print(four)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
five=four.reshape((6,),order='F')
six=four.flatten(order='F')
print(five)
print(six)

[1 3 5 2 4 6]
[1 3 5 2 4 6]


In [17]:
t=np.arange(24)
print(t)
print(t.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [21]:
t1=t.reshape((4,6))
print(t1)
print(t1.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [22]:
a=np.array([9,12,88,14,25])
list_a=a.tolist()
print(list_a)

[9, 12, 88, 14, 25]


In [23]:
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)
print(f.dtype)


2
int16


In [24]:
f1=f.astype(np.int64)
print(f1.dtype)

int64


In [26]:
print(round(random.random(),2))
arr=np.array([random.random() for i in range(10)])
print(np.round(arr,2))

0.18
[0.09 0.54 0.55 0.27 0.05 0.78 0.7  0.95 0.06 0.82]
