In [1]:
from sklearn.linear_model import LinearRegression

In [3]:
x = [[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]]
y = [84.2, 80.6, 80.1, 90, 83.2, 87.6, 79.4, 93.4]

# 实例化API
estimator = LinearRegression()
# 使用fit方法进行训练
estimator.fit(x,y)

# estimator.coef_

estimator.predict([[100, 80]])

array([86.])

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

data=fetch_california_housing(data_home='data')
 # 2.数据集划分
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target,test_size=0.25, random_state=22)

# 3.特征工程-标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.fit_transform(x_test)
# 4.机器学习-线性回归(正规方程)
estimator = LinearRegression()
estimator.fit(x_train, y_train)

# 5.模型评估
# 5.1 获取系数等值
y_predict = estimator.predict(x_test)
print("预测值为:\n", y_predict)
print("模型中的系数为:\n", estimator.coef_)
print("模型中的偏置为:\n", estimator.intercept_)

 # 5.2 评价
# 均方误差
error = mean_squared_error(y_test, y_predict)
print("误差为:\n", error)


预测值为:
 [1.40803975 2.00554943 1.00218594 ... 2.19060071 1.90627246 3.02336701]
模型中的系数为:
 [ 0.82591102  0.11445311 -0.26118374  0.30345645 -0.00706501 -0.04153221
 -0.9107612  -0.88255758]
模型中的偏置为:
 2.069981627260431
误差为:
 0.49134979184329863


In [22]:
from sklearn.linear_model import SGDRegressor

In [33]:
data=fetch_california_housing(data_home='data')
 # 2.数据集划分
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target,test_size=0.25, random_state=22)

# 3.特征工程-标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.fit_transform(x_test)

# 4.机器学习-线性回归(特征方程)
estimator = SGDRegressor(max_iter=1000,learning_rate='constant',eta0=0.0001)
estimator.fit(x_train, y_train)
 # 5.模型评估
# 5.1 获取系数等值
y_predict = estimator.predict(x_test)
print("预测值为:\n", y_predict)
print("模型中的系数为:\n", estimator.coef_)
print("模型中的偏置为:\n", estimator.intercept_)

# 5.2 评价
# 均方误差
error = mean_squared_error(y_test, y_predict)
print("误差为:\n", error)

预测值为:
 [1.41984743 2.00782962 1.02055852 ... 2.20053362 1.89760605 3.02290368]
模型中的系数为:
 [ 0.83636743  0.12376463 -0.2579789   0.29797506 -0.00563925 -0.02521724
 -0.83646445 -0.80698497]
模型中的偏置为:
 [2.07331827]
误差为:
 0.4913233409334916


In [11]:
from sklearn.linear_model import Ridge

In [12]:
def linear_model3():
    """
    线性回归:岭回归
    :return:
    """
    # 1.获取数据
    data=fetch_california_housing(data_home='data')

    # 2.数据集划分
    x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, random_state=22)

    # 3.特征工程-标准化
    transfer = StandardScaler()
    x_train = transfer.fit_transform(x_train)
    x_test = transfer.fit_transform(x_test)

    # 4.机器学习-线性回归(岭回归)
    estimator = Ridge(alpha=1)
    # estimator = RidgeCV(alphas=(0.1, 1, 10))
    estimator.fit(x_train, y_train)

    # 5.模型评估
    # 5.1 获取系数等值
    y_predict = estimator.predict(x_test)
    print("预测值为:\n", y_predict)
    print("模型中的系数为:\n", estimator.coef_)
    print("模型中的偏置为:\n", estimator.intercept_)

    # 5.2 评价
    # 均方误差
    error = mean_squared_error(y_test, y_predict)
    print("误差为:\n", error)

linear_model3()

预测值为:
 [1.40820715 2.00555784 1.00244942 ... 2.19065692 1.90616726 3.02330736]
模型中的系数为:
 [ 0.82587723  0.11454156 -0.2610084   0.30322803 -0.00703095 -0.04153203
 -0.90993973 -0.88172824]
模型中的偏置为:
 2.0699816272604314
误差为:
 0.49134250640715416
