In [2]:
import pandas as pd
import numpy as np

In [2]:
ser_obj = pd.Series(range(10, 20))
print(ser_obj)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [3]:
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values))  #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [4]:
print(ser_obj[0])
ser_obj[9]  #
# 访问不存在的索引下标会报keyerror

10


np.int64(19)

In [5]:
print(ser_obj * 2)
print(ser_obj > 15)


0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [8]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print(ser_obj2.index)
print(ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Index([2001, 2002, 2003], dtype='int64')
17.8


In [9]:
#有点鸡肋
print(ser_obj2.name)  #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-' * 50)
print(ser_obj2.head())  #head默认显示前5行

None
None
--------------------------------------------------
year1
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


In [10]:
t = pd.DataFrame(np.arange(12).reshape((3, 4)))  #默认索引是0-2
print(t)
print('-' * 50)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------


In [11]:
array = np.random.randn(5, 4)
print(array)
print('-' * 50)
df_obj = pd.DataFrame(array)
print(df_obj.head())  #默认显示前5行

[[-2.61133544 -1.27053097  0.07285142  0.86986323]
 [ 0.25828913 -0.66479145 -0.75816169 -1.84749768]
 [-0.56971805  0.64898084 -0.09415107 -0.43642876]
 [-0.9147446  -1.50350764  0.01954264 -0.08395839]
 [-0.00932987 -0.68760368  0.79901649 -0.01637435]]
--------------------------------------------------
          0         1         2         3
0 -2.611335 -1.270531  0.072851  0.869863
1  0.258289 -0.664791 -0.758162 -1.847498
2 -0.569718  0.648981 -0.094151 -0.436429
3 -0.914745 -1.503508  0.019543 -0.083958
4 -0.009330 -0.687604  0.799016 -0.016374


In [12]:
t.loc[0]  #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [13]:
d2 = [{"name": "xiaohong", "age": 32, "tel": 10010},
      {"name": "xiaogang", "tel": 10000},
      {"name": "xiaowang", "age": 22}]
df6 = pd.DataFrame(d2)
print(df6)  #缺失值会用NaN填充
print(type(df6.values))  #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [14]:
pd.Series(1, index=list(range(3, 7)), dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [15]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np

dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [16]:
print(df_obj2.index)  #行索引,重点
#不可改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns)  #列索引，重点
df_obj2.dtypes  #每一列的数据类型，重点

Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object

In [17]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6)  #默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-' * 50)
print(df.index)

                   A         B         C         D
2013-01-01  0.229101 -0.092735 -0.464707  0.619139
2013-01-02 -0.248893  0.396537 -0.436350 -0.737482
2013-01-03 -1.304176 -0.399415 -0.716253 -0.902696
2013-01-04  0.975542  0.511531  0.620195  0.910228
2013-01-05  0.376300 -2.910673  0.235085 -1.650460
2013-01-06 -0.120734  0.990697 -0.874154 -0.423352
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [18]:
#取数据
print(df_obj2)
print('-' * 50)
print(type(df_obj2))
print('-' * 50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-' * 50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[s]
--------------------------------------------------
<class 'pandas.core.series.Series'>


In [19]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [20]:
del (df_obj2['G'])
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [21]:
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.index)

Index([0, 1, 2, 3], dtype='int64')


# 3 常见的Index种类


In [6]:
ser_obj = pd.Series(range(5), index=list("abcde"))
print(ser_obj)
ser_obj.index

a    0
b    1
c    2
d    3
e    4
dtype: int64


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [24]:
# 行索引，不仅可以用索引名，可以用索引位置或来取
print(ser_obj['b'])  #索引名
print(ser_obj.iloc[2])  #位置索引

1
2


In [25]:
# 切片索引
print(ser_obj.iloc[1:3])  #索引位置取数据，左闭右开
print(ser_obj.loc['b':'d'])  #记住索引名  左闭右闭

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [26]:
# 不连续索引
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [27]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool


In [28]:
print('-' * 50)
print(ser_obj[ser_bool])

print(ser_obj[ser_obj > 2])  #取出大于2的元素

--------------------------------------------------
d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


In [3]:
df_obj = pd.DataFrame(np.random.randn(5, 4),
                      columns=['a', 'b', 'c', 'd'])
print(df_obj.head())

          a         b         c         d
0 -0.414485 -0.878530  1.007766  0.631062
1 -0.147731 -0.619559  0.691963 -0.262576
2  1.630783  0.092879  0.172507 -0.660360
3 -1.184289 -1.174673  1.501334 -1.552249
4 -0.880051 -0.748081  0.633947  0.570480


In [4]:
# 列索引
print(df_obj['a'])  # 返回Series类型
print('-' * 50)
print(df_obj[['a']])  # 返回DataFrame类型
print('-' * 50)
print(type(df_obj[['a']]))  # 返回DataFrame类型

0   -0.414485
1   -0.147731
2    1.630783
3   -1.184289
4   -0.880051
Name: a, dtype: float64
--------------------------------------------------
          a
0 -0.414485
1 -0.147731
2  1.630783
3 -1.184289
4 -0.880051
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>


In [7]:
# 标签索引 loc，建议使用loc，效率更高
# Series
print(ser_obj)
print(ser_obj['b':'d'])
print(ser_obj.loc['b':'d'])  #前闭后闭
print('-' * 50)


a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
d    3
dtype: int64
b    1
c    2
d    3
dtype: int64
--------------------------------------------------


In [8]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5, 4),
                      columns=list('abcd'),
                      index=list('abcde'))
print(df_obj)
print('-' * 50)
print(df_obj['a'])  #建议不用,拿的是列
print('-' * 50)
print(df_obj.loc['a'])  #拿的是行
print('-' * 50)


          a         b         c         d
a  0.526026 -1.058210  1.248682 -0.739383
b -0.187368  1.023097 -0.165742  0.633198
c -1.370587 -0.673064 -1.183964  1.686454
d -1.346354 -0.490064  0.812079  0.275658
e  1.174434 -1.562149 -1.640989  0.058134
--------------------------------------------------
a    0.526026
b   -0.187368
c   -1.370587
d   -1.346354
e    1.174434
Name: a, dtype: float64
--------------------------------------------------
a    0.526026
b   -1.058210
c    1.248682
d   -0.739383
Name: a, dtype: float64
--------------------------------------------------


In [9]:
# 第一个参数索引行，第二个参数是列,loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c', 'b':'d'])  #连续索引
print(df_obj.loc[['a', 'c'], ['b', 'd']])  #不连续索引
print(df_obj.loc[['c'], ['b']])  #取一个值,返回的是DataFrame类型
print(df_obj.loc['c', 'b'])  #取一个值

          b         c         d
a -1.058210  1.248682 -0.739383
b  1.023097 -0.165742  0.633198
c -0.673064 -1.183964  1.686454
          b         d
a -1.058210 -0.739383
c -0.673064  1.686454
          b
c -0.673064
-0.6730637112010989


In [10]:
ser_obj
print('-' * 50)
# Series
print(ser_obj[1:3])
print('-' * 50)
print(ser_obj.iloc[1:3])  # 前闭后开[)，效率高


--------------------------------------------------
b    1
c    2
dtype: int64
--------------------------------------------------
b    1
c    2
dtype: int64


In [11]:

# DataFrame，iloc是前闭后开[)
print(df_obj)
print('-' * 50)
print(df_obj.iloc[0:2, 0:2])
print('-' * 50)
print(df_obj.iloc[[0, 2], [0, 2]])  # 不连续索引
print('-' * 50)
print(df_obj.iloc[0, 0])  # 取一个值

          a         b         c         d
a  0.526026 -1.058210  1.248682 -0.739383
b -0.187368  1.023097 -0.165742  0.633198
c -1.370587 -0.673064 -1.183964  1.686454
d -1.346354 -0.490064  0.812079  0.275658
e  1.174434 -1.562149 -1.640989  0.058134
--------------------------------------------------
          a         b
a  0.526026 -1.058210
b -0.187368  1.023097
--------------------------------------------------
          a         c
a  0.526026  1.248682
c -1.370587 -1.183964
--------------------------------------------------
0.5260262439147996


In [12]:
#没有设置行和列索引的DataFrame，iloc和loc的区别
df_obj2 = pd.DataFrame(np.random.randn(5, 4))
print(df_obj2)
print('-' * 50)
print(df_obj2.iloc[0:2])  #左闭右开 2行
print('-' * 50)
print(df_obj2.loc[0:2])  #左闭右闭 3行

          0         1         2         3
0  1.122320  0.986960  1.268999 -0.553231
1 -0.682589 -1.605446  0.360611  0.360934
2 -0.968254 -1.356336 -0.556278  1.377174
3 -0.116615  0.374331  0.432478  2.079731
4  0.034562  0.314744  1.508955  1.569632
--------------------------------------------------
          0         1         2         3
0  1.122320  0.986960  1.268999 -0.553231
1 -0.682589 -1.605446  0.360611  0.360934
--------------------------------------------------
          0         1         2         3
0  1.122320  0.986960  1.268999 -0.553231
1 -0.682589 -1.605446  0.360611  0.360934
2 -0.968254 -1.356336 -0.556278  1.377174


In [13]:
s1 = pd.Series(range(10, 20), index=range(10))
s2 = pd.Series(range(20, 25), index=range(5))
# Series 对齐运算
print('s1+s2: ')
s3 = s1 + s2
print(s3)  #缺失数据默认是NaN  np.nan

s1+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [14]:
#两个长度不同的一维ndarray相加
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([1])  # 长度为1
print(a2.shape)
print(a1 + a2)

(1,)
[2 3 4 5 6]


In [15]:
print(np.isnan(s3[6]))
print('-' * 50)
print(s2.add(s1, fill_value=0))  #未对齐的数据将和填充值做运算
print(s2.sub(s1, fill_value=0))

True
--------------------------------------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5   -15.0
6   -16.0
7   -17.0
8   -18.0
9   -19.0
dtype: float64


In [17]:
#df的对齐运算
df1 = pd.DataFrame(np.ones((2, 2)), columns=['a', 'b'])
df2 = pd.DataFrame(np.ones((3, 3)), columns=['a', 'b', 'c'])
print(df1)
print(df2)
print('-' * 50)
print(df2.dtypes)
print(df1 - df2)
print(df2.sub(df1, fill_value=2))  #未对齐的数据将和填充值做运算

     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
--------------------------------------------------
a    float64
b    float64
c    float64
dtype: object
     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN
     a    b    c
0  0.0  0.0 -1.0
1  0.0  0.0 -1.0
2 -1.0 -1.0 -1.0


In [18]:
df = pd.DataFrame(np.random.randn(5, 4) - 1)
print(df)
print(np.abs(df))

          0         1         2         3
0 -0.246997 -0.230565 -0.858117 -0.769128
1 -0.087230  0.279511 -0.561987 -0.582700
2  0.570058 -1.733503 -0.546222 -0.555152
3 -1.204561 -0.563471 -2.014922 -1.878405
4 -2.388825 -1.067696 -2.249344  0.544550
          0         1         2         3
0  0.246997  0.230565  0.858117  0.769128
1  0.087230  0.279511  0.561987  0.582700
2  0.570058  1.733503  0.546222  0.555152
3  1.204561  0.563471  2.014922  1.878405
4  2.388825  1.067696  2.249344  0.544550


In [19]:
print(df.apply(lambda x: x.max()))

0    0.570058
1    0.279511
2   -0.546222
3    0.544550
dtype: float64
